"""init

Revision ID: ea792b210c30
Revises: 
Create Date: 2025-03-08 16:47:08.015269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea792b210c30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('type', sa.String(length=120), nullable=True),
    sa.Column('environment', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('version', sa.String(length=120), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=True),
    sa.Column('data_type', sa.String(length=120), nullable=True),
    sa.Column('identifiable', sa.Boolean(), nullable=True),
    sa.Column('personal', sa.Boolean(), nullable=True),
    sa.Column('encrypted', sa.Boolean(), nullable=True),
    sa.Column('medical', sa.Boolean(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('standard', sa.String(length=120), nullable=True),
    sa.Column('reportee', sa.String(length=120), nullable=True),
    sa.Column('compliant', sa.Boolean(), nullable=True),
    sa.Column('recommendation', sa.String(length=600), nullable=True),
    sa.Column('more_info_request', sa.String(length=600), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('evidence')
    op.drop_table('entity')
    op.drop_table('system')
    # ### end Alembic commands ###
